spring.application.name=backend
# Configurações de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/lazaros
spring.datasource.username=lazaros_user
spring.datasource.password=senha123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
# "update" faz o Hibernate validar se as tabelas batem com suas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log para ajudar a debugar erros de SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.port=8080